"""Weekly competitive-brief generation.

The report body is built deterministically from the marts (accurate, offline,
reproducible). The executive summary is, when a real LLM provider is configured,
generated by the model from a compact JSON payload; otherwise a clear templated
summary is used. Either way the brief is stored in ``raw.reports``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta

from pipeline.config import Settings, get_settings
from pipeline.logging_setup import get_logger
from pipeline.schemas import utcnow
from pipeline.storage.duckdb_store import Warehouse

log = get_logger(__name__)

LOOKBACK_DAYS = 14
TOP_CHANGES = 8


@dataclass
class ReportResult:
    report_id: str
    title: str
    week_start: date
    summary: str
    body_md: str


def _recent_changes(wh: Warehouse) -> list[tuple]:
    sql_recent = f"""
        SELECT competitor_id, signal_type, change_type, title, summary,
               coalesce(weighted_significance, significance_score, 1) AS sig, detected_at
        FROM main_marts.fct_changes
        WHERE detected_at >= now() - INTERVAL {LOOKBACK_DAYS} DAY
        ORDER BY sig DESC, detected_at DESC
    """
    rows = wh.query(sql_recent)
    if rows:
        return rows
    # Fallback: no activity in the window - summarize the most significant overall.
    return wh.query(
        """
        SELECT competitor_id, signal_type, change_type, title, summary,
               coalesce(weighted_significance, significance_score, 1) AS sig, detected_at
        FROM main_marts.fct_changes
        ORDER BY sig DESC, detected_at DESC
        LIMIT 50
        """
    )


def _names(wh: Warehouse) -> dict[str, str]:
    try:
        rows = wh.query("SELECT competitor_id, name FROM main_marts.dim_competitors")
    except Exception:
        rows = wh.query("SELECT competitor_id, name FROM raw.competitors")
    return {r[0]: r[1] for r in rows}


def _llm_narrative(payload_json: str, settings: Settings) -> str | None:
    """Best-effort LLM executive summary. Returns None to fall back to template."""
    provider = settings.llm_provider.lower()
    prompt = (
        "You are a competitive-intelligence analyst. Using ONLY the JSON data "
        "below, write a concise executive summary (3-4 sentences) of the week's "
        "competitive activity. Be specific and do not invent facts.\n\n"
        f"{payload_json}"
    )
    try:
        if provider == "gemini" and settings.google_api_key:
            import google.generativeai as genai

            genai.configure(api_key=settings.google_api_key)
            model = genai.GenerativeModel(settings.llm_model)
            return (model.generate_content(prompt).text or "").strip() or None
        if provider == "groq" and settings.groq_api_key:
            from groq import Groq

            client = Groq(api_key=settings.groq_api_key)
            resp = client.chat.completions.create(
                model=settings.llm_model, messages=[{"role": "user", "content": prompt}]
            )
            return (resp.choices[0].message.content or "").strip() or None
        if provider == "ollama":
            from openai import OpenAI

            client = OpenAI(base_url=settings.ollama_base_url, api_key="ollama")
            resp = client.chat.completions.create(
                model=settings.ollama_model, messages=[{"role": "user", "content": prompt}]
            )
            return (resp.choices[0].message.content or "").strip() or None
    except Exception as exc:
        log.warning("LLM narrative unavailable (%s); using templated summary", exc)
    return None


def _templated_summary(total: int, ncomp: int, high: int, top: tuple[str, int] | None) -> str:
    lead = (
        f"In the past {LOOKBACK_DAYS} days, **{total}** notable changes were detected across "
        f"**{ncomp}** competitor{'s' if ncomp != 1 else ''}, including **{high}** "
        f"high-significance move{'s' if high != 1 else ''}."
    )
    if top:
        lead += (
            f" Activity was led by **{top[0]}** with {top[1]} change{'s' if top[1] != 1 else ''}."
        )
    return lead


def build_weekly_report(settings: Settings | None = None) -> ReportResult:
    s = settings or get_settings()
    s.ensure_dirs()
    wh = Warehouse.from_settings(s)
    try:
        changes = _recent_changes(wh)
        names = _names(wh)

        # Aggregate per competitor.
        per_comp: dict[str, list[tuple]] = {}
        high = 0
        for row in changes:
            per_comp.setdefault(row[0], []).append(row)
            if (row[5] or 0) >= 4:
                high += 1
        ranked_comps = sorted(per_comp.items(), key=lambda kv: -len(kv[1]))
        top_comp = (
            (names.get(ranked_comps[0][0], ranked_comps[0][0]), len(ranked_comps[0][1]))
            if ranked_comps
            else None
        )

        # Compact JSON payload for the LLM.
        payload = {
            "lookback_days": LOOKBACK_DAYS,
            "total_changes": len(changes),
            "competitors": len(per_comp),
            "high_significance": high,
            "top_changes": [
                {
                    "competitor": names.get(r[0], r[0]),
                    "type": r[1],
                    "title": r[3],
                    "significance": r[5],
                }
                for r in changes[:TOP_CHANGES]
            ],
        }
        summary = _llm_narrative(json.dumps(payload), s) or _templated_summary(
            len(changes), len(per_comp), high, top_comp
        )

        week_start = (datetime.now(UTC) - timedelta(days=7)).date()
        body = _render_markdown(week_start, summary, changes, per_comp, names)
        report_id = f"report-{week_start}"
        wh.upsert_report(
            report_id=report_id,
            title=f"Weekly Competitive Brief - {week_start}",
            week_start=week_start,
            summary=summary.replace("**", "")[:280],
            body_md=body,
            created_at=utcnow(),
        )
        log.info(
            "generated %s (%d changes, %d competitors)", report_id, len(changes), len(per_comp)
        )
        return ReportResult(
            report_id, f"Weekly Competitive Brief - {week_start}", week_start, summary, body
        )
    finally:
        wh.close()


def _render_markdown(
    week_start: date,
    summary: str,
    changes: list[tuple],
    per_comp: dict[str, list[tuple]],
    names: dict[str, str],
) -> str:
    lines: list[str] = []
    lines.append(f"# Weekly Competitive Brief - week of {week_start}")
    lines.append("")
    lines.append("## Executive summary")
    lines.append(summary)
    lines.append("")

    lines.append("## Top changes")
    if changes:
        for r in changes[:TOP_CHANGES]:
            name = names.get(r[0], r[0])
            lines.append(f"- **{name} - {r[3]}** ({r[1]}, significance {r[5]})")
    else:
        lines.append("- No changes detected in the period.")
    lines.append("")

    lines.append("## Per-competitor highlights")
    for cid, rows in sorted(per_comp.items(), key=lambda kv: -len(kv[1])):
        name = names.get(cid, cid)
        lines.append(f"### {name}")
        lines.append(f"{len(rows)} change(s) this period.")
        for r in rows[:3]:
            lines.append(f"- {r[3]} _({r[1]}, sig {r[5]})_")
        lines.append("")

    lines.append("## What to watch")
    watch = sorted(per_comp.items(), key=lambda kv: -len(kv[1]))[:3]
    if watch:
        for cid, rows in watch:
            lines.append(
                f"- **{names.get(cid, cid)}** - sustained activity ({len(rows)} changes); monitor for follow-through."
            )
    else:
        lines.append("- Quiet period - no standout movements.")
    lines.append("")
    return "\n".join(lines)
