"use client";

import { Download, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { AsyncState } from "@/components/async-state";
import { EmptyState } from "@/components/empty-state";
import { Markdown } from "@/components/markdown";
import { PageHeader } from "@/components/page-header";
import { RelativeTime } from "@/components/relative-time";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api";
import { useReport, useReports } from "@/lib/hooks";
import { cn } from "@/lib/utils";

export default function ReportsPage() {
  const reports = useReports();
  const [selected, setSelected] = useState<string | null>(null);

  useEffect(() => {
    if (!selected && reports.data && reports.data.length > 0) setSelected(reports.data[0].id);
  }, [reports.data, selected]);

  const detail = useReport(selected ?? "");

  async function downloadPdf(id: string) {
    try {
      const res = await fetch(api.reportPdfUrl(id));
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        toast.info("PDF export not available yet", {
          description: body?.error?.message ?? body?.detail ?? `Status ${res.status}`,
        });
        return;
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Download failed");
    }
  }

  return (
    <div>
      <PageHeader title="Reports" description="Auto-generated weekly competitive briefs." />

      <AsyncState
        isLoading={reports.isLoading}
        isError={reports.isError}
        error={reports.error}
        onRetry={() => reports.refetch()}
        isEmpty={(reports.data?.length ?? 0) === 0}
        skeleton={<Skeleton className="h-96 w-full" />}
        empty={
          <EmptyState
            icon={FileText}
            title="No reports yet"
            description="Weekly briefs are generated by the report pipeline (Phase 6)."
          />
        }
      >
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          {/* List */}
          <div className="flex flex-col gap-2 lg:col-span-1">
            {reports.data?.map((r) => (
              <button
                key={r.id}
                type="button"
                onClick={() => setSelected(r.id)}
                className={cn(
                  "rounded-lg border p-4 text-left transition-colors hover:bg-secondary/40",
                  selected === r.id && "border-primary/50 bg-secondary/60",
                )}
              >
                <div className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">{r.title}</span>
                </div>
                {r.summary && (
                  <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{r.summary}</p>
                )}
                <RelativeTime value={r.created_at} className="mt-2 block text-xs" />
              </button>
            ))}
          </div>

          {/* Detail */}
          <div className="lg:col-span-2">
            <Card>
              <CardContent className="pt-5">
                {detail.isLoading ? (
                  <div className="space-y-3">
                    <Skeleton className="h-7 w-2/3" />
                    <Skeleton className="h-4 w-full" />
                    <Skeleton className="h-4 w-5/6" />
                    <Skeleton className="h-4 w-4/6" />
                  </div>
                ) : detail.data ? (
                  <>
                    <div className="mb-4 flex items-start justify-between gap-3">
                      <div>
                        <h2 className="text-lg font-semibold">{detail.data.title}</h2>
                        {detail.data.week_start && (
                          <p className="text-xs text-muted-foreground">
                            Week of {detail.data.week_start}
                          </p>
                        )}
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => downloadPdf(detail.data!.id)}
                      >
                        <Download className="h-4 w-4" /> PDF
                      </Button>
                    </div>
                    <Markdown>{detail.data.body_md ?? "_No content._"}</Markdown>
                  </>
                ) : (
                  <p className="text-sm text-muted-foreground">Select a report to read it.</p>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </AsyncState>
    </div>
  );
}
